# Generated by Django 4.1.2 on 2022-10-31 07:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import newapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPortals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('script_path', models.FilePathField(path=newapp.models.files_path)),
                ('parameter', models.JSONField()),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_time', models.DateTimeField()),
                ('parameter', models.JSONField()),
                ('job_portals', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.jobportals')),
            ],
        ),
    ]
